services:
  influxdb:
    image: "influxdb:2.6.1"
    env_file:
      - ./env_files/influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - influxdb-net
  jupyter:
    build: .
    image: jupyter/base-notebook:latest
    networks:
      - influxdb-net
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    volumes:
      - ./notebooks:/app
    env_file:
      - ./env_files/influxv2.env
  grafana:
    image: "grafana/grafana:latest"
    networks:
      - influxdb-net
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./dashboards/:/etc/grafana/dashboards
    env_file:
      - ./env_files/grafana.env
      - ./env_files/influxv2.env

volumes:
  influxdbv2:
    driver: local
  grafana-storage:
    driver: local
networks:
  influxdb-net: {}
