FROM amd64/python:3.9.6-slim-buster

COPY requirements.txt /app/requirements.txt
COPY src/compute_metrics_script.py /app/compute_metrics_script.py
COPY src/gen_data_and_simulate_drift.py /app/gen_data_and_simulate_drift.py
COPY src/fake_data_script.py /app/fake_data_script.py
COPY src/training_script.py /app/training_script.py
COPY src/main.py /app/main.py
COPY datasets/ datasets/
COPY models/ models/
COPY notebooks/pulsar_data_collection-0.0.0-py3-none-any.whl /app/

WORKDIR /app

RUN pip install python-multipart
RUN pip install influxdb-client
RUN pip install /app/pulsar_data_collection-0.0.0-py3-none-any.whl
RUN pip install python-dotenv
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Expose the port that the FastAPI application will run
EXPOSE 8000

# Start the FastAPI app when the container starts
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

# Run Jupyter Notebook when the container launches
# CMD ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root", "--no-browser"]

# CMD ["/bin/bash","-c","./execute_cron_nb.sh"]


# RUN adduser app && chown -R app /app
# USER app
#
# RUN python -m venv /app/.venv
# ENV PATH="/app/.venv/bin:$PATH"
#
# COPY requirements.txt /app/requirements.txt
# COPY main.py /app/main.py
# COPY kidney_disease.pkl /app/kidney_disease.pkl
#
# RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
#
# EXPOSE 8000
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["while true; do sleep 15; done"]
