services:
  influxdb:
    image: "influxdb:2.6.1"
    env_file:
      - ./env_files/influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - influxdb-net
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile_jupyter
    networks:
      - influxdb-net
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    volumes:
      - ./notebooks:/tmp
      - ./src:/src
    env_file:
      - ./env_files/influxv2.env
  grafana:
    image: "grafana/grafana:latest"
    networks:
      - influxdb-net
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./dashboards/:/etc/grafana/dashboards
    env_file:
      - ./env_files/grafana.env
      - ./env_files/influxv2.env
  web:
    build: 
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: "web-container-fastapi"
    ports:
      - "8000:8000"
    env_file:
      - ./env_files/influxv2.env
    depends_on:
      - influxdb
    networks:
      - influxdb-net
volumes:
  influxdbv2:
    driver: local
  grafana-storage:
    driver: local
networks:
  influxdb-net: {}
