services:
  compute-metrics:
    build: .
    links:
      - influxdb
  influxdb:
    build:
      context: ./docker/influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${DB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_USER=${DB_USER}
      - INFLUXDB_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    restart: always
  chronograf:
    image: chronograf:latest
    ports:
      - '8889:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${DB_USER}
      - INFLUXDB_PASSWORD=${DB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./dashboards/:/etc/grafana/dashboards
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage: