{
 "title": "Drift Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "drift" },
   {
    "name": "feature_name",
    "label": "Feature Name",
    "query": "SELECT distinct(\"feature_name\") FROM metrics where metric_type = '$type'"
   },
   {
    "name": "model_id",
    "label": "Model Id",
    "query": "SELECT distinct(\"model_id\") FROM metrics where metric_type = '$type'"
   },
   {
    "name": "model_version",
    "label": "Model Version",
    "query": "SELECT distinct(\"model_version\") FROM metrics where metric_type = '$type'"
   },
   {
    "name": "metric_name",
    "label": "Metric Name",
    "query": "SELECT distinct(\"metric_name\") FROM metrics where metric_type = '$type'"
   }
  ]
 },
 "panels": [
  { "title": "Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://drive.google.com/uc?export=view&id=1qmZiGy4wkwO2o-cFzPM3Sd9D-fa5Vubv\" style=\"height:90%;align=right;\"/>"
   },
   "targets": [
    {
     "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = 'CvM' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT MEAN(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "title": "Comparison",
   "type": "timeseries",
   "description": "Time Series graphs for all metrics for the selected Feature. ",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "alias": "$feature_name-Prediction=TRUE",
     "query": "SELECT \"$feature_name\" FROM prediction where y_pred =1"
    },
    {
     "alias": "$feature_name-Prediction=FALSE",
     "query": "SELECT \"$feature_name\" FROM prediction where y_pred =0"
    },
    {
     "alias": "$feature_name-Moving Avg",
     "query": "SELECT moving_average(mean(\"$feature_name\"), 2) FROM prediction WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "query": "SELECT STDDEV(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "variance" ] } },
   "targets": [
    {
     "query": "SELECT median(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(DISTINCT(metric_name)) FROM metrics WHERE drift_status='True' AND metric_type = '$type' and feature_name = '$feature_name' and model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 7 },
   "targets": [
    {
     "query": "SELECT DISTINCT(metric_name) FROM metrics WHERE drift_status='True' AND metric_type = '$type' and feature_name = '$feature_name' and model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "variance" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(\"$feature_name\") FROM prediction where model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "title": "First Value Inserted on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "SELECT time, metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and model_id = '$model_id' and model_version = '$model_version' ORDER BY time ASC LIMIT 1"
    }
   ]
  },
  {
   "title": "Last Value Inserted on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT time, metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and model_id = '$model_id' and model_version = '$model_version' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Brown Forsythe Test",
   "type": "timeseries",
   "description": "Brown Forsythe test metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "Bf test",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'bftest' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Ttest",
   "type": "timeseries",
   "description": "Ttest metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "alias": "T-test",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'ttest' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Mann-Whitney U Test",
   "type": "timeseries",
   "description": "Manwu metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "Mann WU test",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'manwu' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Kolmogorov Smirnov",
   "type": "timeseries",
   "description": "Kolmogorov Smirnov metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "alias": "KS",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'ks_2samp' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Wasserstein Distance",
   "type": "timeseries",
   "description": "Wasserstein metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Wasserstein",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'wasserstein' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Levene Test",
   "type": "timeseries",
   "description": "Levene metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "alias": "Levene",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'levene' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Kullback-Leibler Divergence",
   "type": "timeseries",
   "description": "Kullback-Leibler metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "KL",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'kl' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Cramer-von Mises",
   "type": "timeseries",
   "description": "Cramer-von Mises metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "alias": "CvM",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'CvM' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Population Stability Index",
   "type": "timeseries",
   "description": "Population Stability Index metric corresponding to the Feature - $feature_name. Click on the data points to navigate to more detailed view.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "psi",
     "query": "SELECT metric_value FROM metrics where metric_type = '$type' and feature_name = '$feature_name' and metric_name = 'psi' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "title": "Perfomence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Precision",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = 'precision'"
      }
     ]
    },
    {
     "title": "Precision",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'precision'"
      }
     ]
    },
    {
     "title": "Recall",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'recall'"
      }
     ]
    },
    {
     "title": "F1",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'f1'"
      }
     ]
    },
    {
     "title": "Brier",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'brier'"
      }
     ]
    },
    {
     "title": "Brier",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'brier'"
      }
     ]
    },
    {
     "title": "MAE",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'mae'"
      }
     ]
    },
    {
     "title": "MAPE",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'mape'"
      }
     ]
    },
    {
     "title": "R2",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "query": "SELECT value FROM metrics_db where type = '$type' and feature = '$feature_name' and metric_name = 'r2'"
      }
     ]
    }
   ]
  }
 ]
}