{
 "title": "DriftDetailDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "query": "drift" },
   {
    "name": "model_id",
    "query": "SELECT distinct(\"model_id\") FROM metrics where type = '$type'"
   },
   {
    "name": "model_version",
    "query": "SELECT distinct(\"model_version\") FROM metrics where type = '$type'"
   },
   {
    "name": "feature_name",
    "query": "SELECT distinct(\"feature\") FROM metrics where type = '$type'"
   },
   {
    "name": "metric_name",
    "query": "SELECT distinct(\"metric_name\") FROM metrics where type = '$type'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://drive.google.com/uc?export=view&id=1qmZiGy4wkwO2o-cFzPM3Sd9D-fa5Vubv\" style=\"height:90%;align=right;\"/>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version' "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version' "
    }
   ]
  },
  {
   "title": "Last Value Inserted at",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT time, value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version' "
    }
   ]
  },
  {
   "title": "Drift Detail for Feature - $feature_name and Metric - $metric_name",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 15, "x": 9, "y": 5 },
   "targets": [
    {
     "alias": "$metric_name value",
     "query": "SELECT value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version'"
    },
    {
     "alias": "threshold",
     "query": "SELECT threshold FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(value) FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name'  and model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  },
  {
   "title": "Heatmap for Metrics vs Time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT time, value FROM metrics where type = '$type' and feature = '$feature_name' and metric_name = '$metric_name' and model_id = '$model_id' and model_version = '$model_version' and $timeFilter"
    }
   ]
  }
 ]
}